base:
  image: ubuntu:14.04
  working_dir: /srv
  volumes:
    - .:/srv

web:
  extends: {'service': 'base'}
  build: .
  ports:
    - "8010:5000"
  links:
     - db

sass:
  extends: {'service': 'base'}
  image: ubuntudesign/sass
  command: sass --cache-location /.sass-cache --update static/css --force -E "UTF-8"

sass-watch:
  extends: {'service': 'sass', 'file': 'docker-compose.yml'}
  command: sass --cache-location /.sass-cache --watch static/css -E "UTF-8"

db:
  image: postgres

